CREATE TABLE IF NOT EXISTS logs_apartment_registration_info (
                                                                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                                operation_type varchar,
                                                                date_operation timestamp DEFAULT now(),
                                                                logs_message varchar
);

CREATE SEQUENCE logs_apartment_registration_info_sequence;